llm:
  model: gpt-4
  api_key: your_openai_api_key

agents:
  researcher:
    search_apis:
      - google
      - scopus
    max_sources: 10
  
  writer:
    style_guide: default
    tone: professional
  
  editor:
    grammar_checker: grammarly
    style_guide: chicago

  seo:
    tools:
      - semrush
      - ahrefs
    
  image:
    generator: dall-e
    style: modern

  publisher:
    platforms:
      - wordpress
      - medium

memory:
  short_term_size: 100
  storage_path: ./data/memory
